name: 'Branch Tag'
description: 'Test Branch Commit Tag'

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Add file
      run: |
        touch .keep
      shell: bash

    - name: Add and Commit
      uses: EndBug/add-and-commit@v8 # You can change this to use a specific version.
      with:
        new_branch: release/${{ github.sha }}
        tag: v1 --force
